Rails.application.routes.draw do
  namespace :admin do
    resources :media do
      collection { delete :bulk_destroy }
    end
    resources :categories
    resources :pages
    resources :posts
    # Phase 3 commerce
    resources :products
    resources :orders, only: %i[index show]
    resources :users do
      member do
        patch :ban
        patch :unban
        post  :impersonate
      end
      collection do
        patch :bulk_role
      end
    end

    resources :series

    # Embed widget preview — returns rendered iframe partial for a given URL
    get "embeds/preview", to: "embeds#preview", as: :embed_preview

    # Site-wide settings (invite_only toggle etc.) — admin role only
    resource :settings, only: %i[show update], controller: "site_settings"

    # End an active impersonation session (Login-as exit)
    resource :impersonation, only: :destroy

    root to: "pages#index"
  end
  # Stripe webhook endpoint — no CSRF, verified via signature
  post "webhooks/stripe", to: "stripe_webhooks#create", as: :webhooks_stripe

  # Auth routes (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # Public CMS routes
  root "pages#show", defaults: { id: "home" }

  resources :posts, path: "blog", only: %i[index show], param: :slug
  resources :categories, path: "topics", only: :show, param: :slug
  resources :series, path: "series", only: :show, param: :slug

  # Self-service registration and email verification
  get  "register",         to: "registrations#new",               as: :new_registration
  post "register",         to: "registrations#create",            as: :registrations
  get  "register/verify",  to: "registrations#verify_email",      as: :verify_email_registration
  post "register/resend",  to: "registrations#resend_verification", as: :resend_verification_registration

  # Member profiles (public) — /members/:display_name
  resources :members, only: :show, param: :display_name

  # Account settings (authenticated) — /settings and /settings/update_password
  resource :settings, only: %i[show update] do
    patch :update_password
  end

  # RSS feed
  get "feed.xml", to: "feed#show", as: :feed, defaults: { format: :xml }

  # Public shop — must come before the page catch-all
  get "/shop",       to: "shop#index", as: :shop
  get "/shop/:slug", to: "shop#show",  as: :shop_product

  # Shopping cart
  resource  :cart, only: :show
  scope "/cart" do
    post   "items",     to: "carts#add_item",    as: :cart_items
    patch  "items/:id", to: "carts#update_item", as: :cart_item
    delete "items/:id", to: "carts#remove_item"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Page catch-all must be last so it does not swallow /blog, /topics, etc.
  get "/*id", to: "pages#show", as: :page
end
