Rails.application.routes.draw do
  namespace :admin do
    resources :media do
      collection { delete :bulk_destroy }
    end
    resources :categories
    resources :pages
    resources :posts
    # Phase 4 community
    resources :forums
    resources :forum_threads, only: %i[index show edit update destroy] do
      member do
        patch :lock
        patch :pin
      end
    end
    resources :forum_replies, only: %i[index show destroy]
    # Phase 6 album manager
    resources :albums do
      member { patch :publish }
      resources :tracks do
        collection { patch :reorder }
        resources :track_comments, only: %i[create destroy], path: "comments"
      end
    end
    resource :album_download_report, only: :show, controller: :album_download_report

    # Phase 5 admin group chat
    get  "chat",                                                       to: "chat#index",            as: :chat
    post "chat/channels",                                              to: "chat#create_channel",   as: :chat_channels
    get  "chat/:id",                                                   to: "chat#show",             as: :chat_channel
    post "chat/:channel_id/messages",                                  to: "chat_messages#create",  as: :chat_channel_messages
    patch "chat/:channel_id/messages/:id",                             to: "chat_messages#update",  as: :chat_channel_message
    delete "chat/:channel_id/messages/:id",                            to: "chat_messages#destroy"
    post "chat/:channel_id/messages/:message_id/reactions",            to: "chat_reactions#create", as: :chat_reaction
    delete "chat/:channel_id/messages/:message_id/reactions/:emoji",   to: "chat_reactions#destroy"

    # Phase 4.2 moderation queue
    resources :moderation, only: :index do
      member do
        patch  :approve
        delete :remove
      end
    end
    # Phase 3 commerce
    resources :products
    resources :orders, only: %i[index show] do
      member { post :refund }
    end
    # Rails would infer Admin::RevenuesController; override to Admin::RevenueController.
    resource :revenue, only: :show, controller: :revenue
    resources :users do
      member do
        patch :ban
        patch :unban
        post  :impersonate
      end
      collection do
        patch :bulk_role
      end
    end

    resources :series

    # Embed widget preview — returns rendered iframe partial for a given URL
    get "embeds/preview", to: "embeds#preview", as: :embed_preview

    # Site-wide settings (invite_only toggle etc.) — admin role only
    resource :settings, only: %i[show update], controller: "site_settings"

    # End an active impersonation session (Login-as exit)
    resource :impersonation, only: :destroy

    root to: "pages#index"
  end
  # Stripe webhook endpoint — no CSRF, verified via signature
  post "webhooks/stripe", to: "stripe_webhooks#create", as: :webhooks_stripe

  # Auth routes (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # Public CMS routes
  root "pages#show", defaults: { id: "home" }

  resources :posts, path: "blog", only: %i[index show], param: :slug
  resources :categories, path: "topics", only: :show, param: :slug
  resources :series, path: "series", only: :show, param: :slug

  # Self-service registration and email verification
  get  "register",         to: "registrations#new",               as: :new_registration
  post "register",         to: "registrations#create",            as: :registrations
  get  "register/verify",  to: "registrations#verify_email",      as: :verify_email_registration
  post "register/resend",  to: "registrations#resend_verification", as: :resend_verification_registration

  # Member profiles (public) — /members/:display_name
  resources :members, only: :show, param: :display_name

  # Account settings (authenticated) — /settings and /settings/update_password
  resource :settings, only: %i[show update] do
    patch :update_password
  end

  # RSS feed
  get "feed.xml", to: "feed#show", as: :feed, defaults: { format: :xml }

  # Public shop — must come before the page catch-all
  get "/shop",       to: "shop#index", as: :shop
  get "/shop/:slug", to: "shop#show",  as: :shop_product

  # Shopping cart
  resource  :cart, only: :show
  scope "/cart" do
    post   "items",     to: "carts#add_item",    as: :cart_items
    patch  "items/:id", to: "carts#update_item", as: :cart_item
    delete "items/:id", to: "carts#remove_item"
  end

  # Notification bell
  resources :notifications, only: :index

  # Account — authenticated user area
  scope "/account", as: :account do
    get "downloads",     to: "downloads#index", as: :downloads
    get "downloads/:id", to: "downloads#show",  as: :download
  end

  # Checkout (embedded Stripe Payment Element)
  get  "/checkout",             to: "checkouts#new",          as: :checkout
  post "/checkout",             to: "checkouts#create"
  get  "/checkout/confirmation", to: "checkouts#confirmation", as: :checkout_confirmation

  get "up" => "rails/health#show", as: :rails_health_check

  # Public album catalogue — must come before the page catch-all
  get "/albums",       to: "albums#index", as: :albums
  get "/albums/:slug", to: "albums#show",  as: :album

  # Community — must be before the page catch-all
  get  "/community",                       to: "community#index",         as: :community
  get  "/community/:slug/new",             to: "community#new_thread",    as: :new_community_thread
  post "/community/:slug/threads",         to: "community#create_thread", as: :community_threads
  get  "/community/:slug/:id",             to: "community#thread",        as: :community_thread
  post   "/community/:slug/:id/replies",                    to: "community#create_reply",  as: :community_thread_replies
  delete "/community/:slug/:id/replies/:reply_id",         to: "community#destroy_reply", as: :community_thread_reply
  post   "/community/:slug/:id/replies/:reply_id/like",   to: "community#like_reply",    as: :like_community_reply
  post   "/community/:slug/:id/replies/:reply_id/report", to: "community#report_reply",  as: :report_community_reply
  get  "/community/:slug",                              to: "community#forum",         as: :community_forum

  # Page catch-all must be last so it does not swallow /blog, /topics, etc.
  get "/*id", to: "pages#show", as: :page
end
