Rails.application.routes.draw do
  namespace :admin do
    resources :media do
      collection { delete :bulk_destroy }
    end
    resources :categories
    resources :pages
    resources :posts
    resources :users

    # Embed widget preview — returns rendered iframe partial for a given URL
    get "embeds/preview", to: "embeds#preview", as: :embed_preview

    root to: "pages#index"
  end
  # Auth routes (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # Public CMS routes
  root "pages#show", defaults: { id: "home" }

  resources :posts, path: "blog", only: %i[index show], param: :slug
  resources :categories, path: "topics", only: :show, param: :slug

  get "up" => "rails/health#show", as: :rails_health_check

  # Page catch-all must be last so it does not swallow /blog, /topics, etc.
  get "/*id", to: "pages#show", as: :page
end
